#pragma once

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum vltl_asm_register_8086 {
    VLTL_ASM_REGISTER_8086_UNSET,
    VLTL_ASM_REGISTER_8086_INVALID,

    VLTL_ASM_REGISTER_8086_AX,
    VLTL_ASM_REGISTER_8086_AH,
    VLTL_ASM_REGISTER_8086_AL,

    VLTL_ASM_REGISTER_8086_BX,
    VLTL_ASM_REGISTER_8086_BH,
    VLTL_ASM_REGISTER_8086_BL,

    VLTL_ASM_REGISTER_8086_CX,
    VLTL_ASM_REGISTER_8086_CH,
    VLTL_ASM_REGISTER_8086_CL,

    VLTL_ASM_REGISTER_8086_DX,
    VLTL_ASM_REGISTER_8086_DH,
    VLTL_ASM_REGISTER_8086_DL,

    VLTL_ASM_REGISTER_8086_SP,
    VLTL_ASM_REGISTER_8086_BP,
    VLTL_ASM_REGISTER_8086_SI,
    VLTL_ASM_REGISTER_8086_DI,

    VLTL_ASM_REGISTER_8086_EOF
} Vltl_asm_register_8086;

typedef enum vltl_asm_register_intel32 {
    VLTL_ASM_REGISTER_INTEL32_UNSET,
    VLTL_ASM_REGISTER_INTEL32_INVALID,

    VLTL_ASM_REGISTER_INTEL32_EAX,
    VLTL_ASM_REGISTER_INTEL32_EBX,
    VLTL_ASM_REGISTER_INTEL32_ECX,
    VLTL_ASM_REGISTER_INTEL32_EDX,
    VLTL_ASM_REGISTER_INTEL32_ESI,
    VLTL_ASM_REGISTER_INTEL32_EDI,
    VLTL_ASM_REGISTER_INTEL32_EBP,
    VLTL_ASM_REGISTER_INTEL32_ESP,

    VLTL_ASM_REGISTER_INTEL32_EOF
} Vltl_asm_register_intel32;

typedef enum vltl_asm_register_amd64 {
    VLTL_ASM_REGISTER_AMD64_UNSET,
    VLTL_ASM_REGISTER_AMD64_INVALID,

    VLTL_ASM_REGISTER_AMD64_RAX,
    VLTL_ASM_REGISTER_AMD64_RBX,
    VLTL_ASM_REGISTER_AMD64_RCX,
    VLTL_ASM_REGISTER_AMD64_RDX,
    VLTL_ASM_REGISTER_AMD64_RSI,
    VLTL_ASM_REGISTER_AMD64_RDI,
    VLTL_ASM_REGISTER_AMD64_RBP,
    VLTL_ASM_REGISTER_AMD64_RSP,
    VLTL_ASM_REGISTER_AMD64_R8,
    VLTL_ASM_REGISTER_AMD64_R9,
    VLTL_ASM_REGISTER_AMD64_R10,
    VLTL_ASM_REGISTER_AMD64_R11,
    VLTL_ASM_REGISTER_AMD64_R12,
    VLTL_ASM_REGISTER_AMD64_R13,
    VLTL_ASM_REGISTER_AMD64_R14,
    VLTL_ASM_REGISTER_AMD64_R15,

    VLTL_ASM_REGISTER_AMD64_EOF
} Vltl_asm_register_amd64;

extern const char *const vltl_asm_register_detokenize_table[];

#ifdef __cplusplus
}
#endif
